"""Add VehicleType model and FK to Car

Revision ID: 089ea3a2a8c5
Revises: a9b5a10fe344
Create Date: 2025-04-27 14:29:41.940482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089ea3a2a8c5'
down_revision = 'a9b5a10fe344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # Add vehicle_type_id as nullable first
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_type_id', sa.Integer(), nullable=True))
        batch_op.drop_column('vehicle_type')

    # Insert default vehicle types
    op.execute(
        "INSERT INTO vehicle_type (name, display_name) VALUES "
        "('car', 'Car'),"
        "('motorcycle', 'Motorcycle'),"
        "('boat', 'Boat')"
    )
    # Set all existing cars to 'car'
    op.execute(
        """
        UPDATE car SET vehicle_type_id = (
            SELECT id FROM vehicle_type WHERE name = 'car'
        ) WHERE vehicle_type_id IS NULL
        """
    )
    # Make vehicle_type_id NOT NULL
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('vehicle_type_id', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_type', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vehicle_type_id')

    op.drop_table('vehicle_type')
    # ### end Alembic commands ###
