"""Add is_admin to User model

Revision ID: 799c655b0349
Revises: 089ea3a2a8c5
Create Date: 2025-04-27 14:39:55.513595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799c655b0349'
down_revision = '089ea3a2a8c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'vehicle_type', ['vehicle_type_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
