"""Add distance_unit to user and mileage to vehicle

Revision ID: 7f0d362b4f74
Revises: 951b8dd55b52
Create Date: 2025-04-27 16:58:42.685531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f0d362b4f74'
down_revision = '951b8dd55b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance_unit', sa.String(length=4), nullable=True))
    op.execute("UPDATE \"user\" SET distance_unit = 'km'")
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('distance_unit', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('distance_unit')

    # ### end Alembic commands ###
