"""Add vehicle mileage

Revision ID: 951b8dd55b52
Revises: rename_car_to_vehicle
Create Date: 2025-04-27 16:50:18.711441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951b8dd55b52'
down_revision = 'rename_car_to_vehicle'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mileage', sa.Integer(), nullable=False))

    with op.batch_alter_table('vehicle_type', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['order'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_type', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('mileage')

    # ### end Alembic commands ###
