"""Add order column to VehicleType

Revision ID: a185602cab2c
Revises: 799c655b0349
Create Date: 2025-04-27 14:48:45.374940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a185602cab2c'
down_revision = '799c655b0349'
branch_labels = None
depends_on = None


def upgrade():
    # Add the column as nullable first
    with op.batch_alter_table('vehicle_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    # Set order for all existing vehicle types (by id order)
    op.execute(
        """
        UPDATE vehicle_type
        SET "order" = sub.rn
        FROM (
            SELECT id, ROW_NUMBER() OVER (ORDER BY id) - 1 AS rn
            FROM vehicle_type
        ) AS sub
        WHERE vehicle_type.id = sub.id
        """
    )

    # Make the column NOT NULL
    with op.batch_alter_table('vehicle_type', schema=None) as batch_op:
        batch_op.alter_column('order', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_type', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
