"""Add email field to OwnershipRecord for pending transfers

Revision ID: d33d182876bc
Revises: 4187bbc97825
Create Date: 2025-04-27 20:34:01.057145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd33d182876bc'
down_revision = '4187bbc97825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ownership_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_ownership_record_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ownership_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ownership_record_email'))
        batch_op.drop_column('email')

    # ### end Alembic commands ###
